// Code generated by MockGen. DO NOT EDIT.
// Source: subject_service.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/student-api/models"
)

// MocksubjectDatastore is a mock of subjectDatastore interface.
type MocksubjectDatastore struct {
	ctrl     *gomock.Controller
	recorder *MocksubjectDatastoreMockRecorder
}

// MocksubjectDatastoreMockRecorder is the mock recorder for MocksubjectDatastore.
type MocksubjectDatastoreMockRecorder struct {
	mock *MocksubjectDatastore
}

// NewMocksubjectDatastore creates a new mock instance.
func NewMocksubjectDatastore(ctrl *gomock.Controller) *MocksubjectDatastore {
	mock := &MocksubjectDatastore{ctrl: ctrl}
	mock.recorder = &MocksubjectDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksubjectDatastore) EXPECT() *MocksubjectDatastoreMockRecorder {
	return m.recorder
}

// GetAllSubject mocks base method.
func (m *MocksubjectDatastore) GetAllSubject() ([]models.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSubject")
	ret0, _ := ret[0].([]models.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSubject indicates an expected call of GetAllSubject.
func (mr *MocksubjectDatastoreMockRecorder) GetAllSubject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSubject", reflect.TypeOf((*MocksubjectDatastore)(nil).GetAllSubject))
}

// GetSubject mocks base method.
func (m *MocksubjectDatastore) GetSubject(arg0 int) (models.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubject", arg0)
	ret0, _ := ret[0].(models.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubject indicates an expected call of GetSubject.
func (mr *MocksubjectDatastoreMockRecorder) GetSubject(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubject", reflect.TypeOf((*MocksubjectDatastore)(nil).GetSubject), arg0)
}

// InsertSubject mocks base method.
func (m *MocksubjectDatastore) InsertSubject(arg0 models.Subject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSubject", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSubject indicates an expected call of InsertSubject.
func (mr *MocksubjectDatastoreMockRecorder) InsertSubject(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSubject", reflect.TypeOf((*MocksubjectDatastore)(nil).InsertSubject), arg0)
}
