// Code generated by MockGen. DO NOT EDIT.
// Source: enrolment_service.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/student-api/models"
)

// MockenrolmentDatastore is a mock of enrolmentDatastore interface.
type MockenrolmentDatastore struct {
	ctrl     *gomock.Controller
	recorder *MockenrolmentDatastoreMockRecorder
}

// MockenrolmentDatastoreMockRecorder is the mock recorder for MockenrolmentDatastore.
type MockenrolmentDatastoreMockRecorder struct {
	mock *MockenrolmentDatastore
}

// NewMockenrolmentDatastore creates a new mock instance.
func NewMockenrolmentDatastore(ctrl *gomock.Controller) *MockenrolmentDatastore {
	mock := &MockenrolmentDatastore{ctrl: ctrl}
	mock.recorder = &MockenrolmentDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockenrolmentDatastore) EXPECT() *MockenrolmentDatastoreMockRecorder {
	return m.recorder
}

// EnrolStudent mocks base method.
func (m *MockenrolmentDatastore) EnrolStudent(stuId, subId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnrolStudent", stuId, subId)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnrolStudent indicates an expected call of EnrolStudent.
func (mr *MockenrolmentDatastoreMockRecorder) EnrolStudent(stuId, subId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnrolStudent", reflect.TypeOf((*MockenrolmentDatastore)(nil).EnrolStudent), stuId, subId)
}

// GetAllSubjectByStudent mocks base method.
func (m *MockenrolmentDatastore) GetAllSubjectByStudent(stuId int) ([]models.EnrolmentList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSubjectByStudent", stuId)
	ret0, _ := ret[0].([]models.EnrolmentList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSubjectByStudent indicates an expected call of GetAllSubjectByStudent.
func (mr *MockenrolmentDatastoreMockRecorder) GetAllSubjectByStudent(stuId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSubjectByStudent", reflect.TypeOf((*MockenrolmentDatastore)(nil).GetAllSubjectByStudent), stuId)
}
