// Code generated by MockGen. DO NOT EDIT.
// Source: student_service.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/student-api/models"
)

// MockstudentDatastore is a mock of studentDatastore interface.
type MockstudentDatastore struct {
	ctrl     *gomock.Controller
	recorder *MockstudentDatastoreMockRecorder
}

// MockstudentDatastoreMockRecorder is the mock recorder for MockstudentDatastore.
type MockstudentDatastoreMockRecorder struct {
	mock *MockstudentDatastore
}

// NewMockstudentDatastore creates a new mock instance.
func NewMockstudentDatastore(ctrl *gomock.Controller) *MockstudentDatastore {
	mock := &MockstudentDatastore{ctrl: ctrl}
	mock.recorder = &MockstudentDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstudentDatastore) EXPECT() *MockstudentDatastoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockstudentDatastore) Delete(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockstudentDatastoreMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockstudentDatastore)(nil).Delete), arg0)
}

// Insert mocks base method.
func (m *MockstudentDatastore) Insert(arg0 models.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockstudentDatastoreMockRecorder) Insert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockstudentDatastore)(nil).Insert), arg0)
}

// Read mocks base method.
func (m *MockstudentDatastore) Read(arg0 int) (models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockstudentDatastoreMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockstudentDatastore)(nil).Read), arg0)
}

// ReadAll mocks base method.
func (m *MockstudentDatastore) ReadAll() ([]models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll")
	ret0, _ := ret[0].([]models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockstudentDatastoreMockRecorder) ReadAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockstudentDatastore)(nil).ReadAll))
}

// ReadByName mocks base method.
func (m *MockstudentDatastore) ReadByName(arg0 string) ([]models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadByName", arg0)
	ret0, _ := ret[0].([]models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadByName indicates an expected call of ReadByName.
func (mr *MockstudentDatastoreMockRecorder) ReadByName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadByName", reflect.TypeOf((*MockstudentDatastore)(nil).ReadByName), arg0)
}

// Update mocks base method.
func (m *MockstudentDatastore) Update(arg0 models.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockstudentDatastoreMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockstudentDatastore)(nil).Update), arg0)
}
