// Code generated by MockGen. DO NOT EDIT.
// Source: subject_handler.go

// Package handlers is a generated GoMock package.
package handlers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/student-api/models"
)

// MocksubjectService is a mock of subjectService interface.
type MocksubjectService struct {
	ctrl     *gomock.Controller
	recorder *MocksubjectServiceMockRecorder
}

// MocksubjectServiceMockRecorder is the mock recorder for MocksubjectService.
type MocksubjectServiceMockRecorder struct {
	mock *MocksubjectService
}

// NewMocksubjectService creates a new mock instance.
func NewMocksubjectService(ctrl *gomock.Controller) *MocksubjectService {
	mock := &MocksubjectService{ctrl: ctrl}
	mock.recorder = &MocksubjectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksubjectService) EXPECT() *MocksubjectServiceMockRecorder {
	return m.recorder
}

// GetAllSubjectService mocks base method.
func (m *MocksubjectService) GetAllSubjectService() ([]models.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSubjectService")
	ret0, _ := ret[0].([]models.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSubjectService indicates an expected call of GetAllSubjectService.
func (mr *MocksubjectServiceMockRecorder) GetAllSubjectService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSubjectService", reflect.TypeOf((*MocksubjectService)(nil).GetAllSubjectService))
}

// GetSubjectService mocks base method.
func (m *MocksubjectService) GetSubjectService(id int) (models.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubjectService", id)
	ret0, _ := ret[0].(models.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubjectService indicates an expected call of GetSubjectService.
func (mr *MocksubjectServiceMockRecorder) GetSubjectService(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubjectService", reflect.TypeOf((*MocksubjectService)(nil).GetSubjectService), id)
}

// InsertSubjectService mocks base method.
func (m *MocksubjectService) InsertSubjectService(subject models.Subject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSubjectService", subject)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSubjectService indicates an expected call of InsertSubjectService.
func (mr *MocksubjectServiceMockRecorder) InsertSubjectService(subject interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSubjectService", reflect.TypeOf((*MocksubjectService)(nil).InsertSubjectService), subject)
}
