// Code generated by MockGen. DO NOT EDIT.
// Source: student_handler.go

// Package handlers is a generated GoMock package.
package handlers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/student-api/models"
)

// Mockdatastore is a mock of datastore interface.
type Mockdatastore struct {
	ctrl     *gomock.Controller
	recorder *MockdatastoreMockRecorder
}

// MockdatastoreMockRecorder is the mock recorder for Mockdatastore.
type MockdatastoreMockRecorder struct {
	mock *Mockdatastore
}

// NewMockdatastore creates a new mock instance.
func NewMockdatastore(ctrl *gomock.Controller) *Mockdatastore {
	mock := &Mockdatastore{ctrl: ctrl}
	mock.recorder = &MockdatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdatastore) EXPECT() *MockdatastoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *Mockdatastore) Delete(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockdatastoreMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockdatastore)(nil).Delete), arg0)
}

// Insert mocks base method.
func (m *Mockdatastore) Insert(arg0 models.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockdatastoreMockRecorder) Insert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*Mockdatastore)(nil).Insert), arg0)
}

// Read mocks base method.
func (m *Mockdatastore) Read(arg0 int) (models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockdatastoreMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*Mockdatastore)(nil).Read), arg0)
}

// ReadAll mocks base method.
func (m *Mockdatastore) ReadAll() (models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll")
	ret0, _ := ret[0].(models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockdatastoreMockRecorder) ReadAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*Mockdatastore)(nil).ReadAll))
}

// Update mocks base method.
func (m *Mockdatastore) Update(arg0 models.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockdatastoreMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*Mockdatastore)(nil).Update), arg0)
}
