// Code generated by MockGen. DO NOT EDIT.
// Source: student_handler.go

// Package handlers is a generated GoMock package.
package handlers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/student-api/models"
)

// MockstudentService is a mock of studentService interface.
type MockstudentService struct {
	ctrl     *gomock.Controller
	recorder *MockstudentServiceMockRecorder
}

// MockstudentServiceMockRecorder is the mock recorder for MockstudentService.
type MockstudentServiceMockRecorder struct {
	mock *MockstudentService
}

// NewMockstudentService creates a new mock instance.
func NewMockstudentService(ctrl *gomock.Controller) *MockstudentService {
	mock := &MockstudentService{ctrl: ctrl}
	mock.recorder = &MockstudentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstudentService) EXPECT() *MockstudentServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockstudentService) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockstudentServiceMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockstudentService)(nil).Delete), arg0)
}

// EnrolStudentSvs mocks base method.
func (m *MockstudentService) EnrolStudentSvs(stuId, subId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnrolStudentSvs", stuId, subId)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnrolStudentSvs indicates an expected call of EnrolStudentSvs.
func (mr *MockstudentServiceMockRecorder) EnrolStudentSvs(stuId, subId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnrolStudentSvs", reflect.TypeOf((*MockstudentService)(nil).EnrolStudentSvs), stuId, subId)
}

// GetstudentBySubSvs mocks base method.
func (m *MockstudentService) GetstudentBySubSvs(stuId string) ([]models.EnrolmentList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetstudentBySubSvs", stuId)
	ret0, _ := ret[0].([]models.EnrolmentList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetstudentBySubSvs indicates an expected call of GetstudentBySubSvs.
func (mr *MockstudentServiceMockRecorder) GetstudentBySubSvs(stuId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetstudentBySubSvs", reflect.TypeOf((*MockstudentService)(nil).GetstudentBySubSvs), stuId)
}

// InsertService mocks base method.
func (m *MockstudentService) InsertService(arg0 models.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertService", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertService indicates an expected call of InsertService.
func (mr *MockstudentServiceMockRecorder) InsertService(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertService", reflect.TypeOf((*MockstudentService)(nil).InsertService), arg0)
}

// ReadAllService mocks base method.
func (m *MockstudentService) ReadAllService() ([]models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAllService")
	ret0, _ := ret[0].([]models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAllService indicates an expected call of ReadAllService.
func (mr *MockstudentServiceMockRecorder) ReadAllService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAllService", reflect.TypeOf((*MockstudentService)(nil).ReadAllService))
}

// ReadByDetailService mocks base method.
func (m *MockstudentService) ReadByDetailService(arg0, arg1 string) ([]models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadByDetailService", arg0, arg1)
	ret0, _ := ret[0].([]models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadByDetailService indicates an expected call of ReadByDetailService.
func (mr *MockstudentServiceMockRecorder) ReadByDetailService(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadByDetailService", reflect.TypeOf((*MockstudentService)(nil).ReadByDetailService), arg0, arg1)
}

// ReadByIdService mocks base method.
func (m *MockstudentService) ReadByIdService(arg0 int) (models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadByIdService", arg0)
	ret0, _ := ret[0].(models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadByIdService indicates an expected call of ReadByIdService.
func (mr *MockstudentServiceMockRecorder) ReadByIdService(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadByIdService", reflect.TypeOf((*MockstudentService)(nil).ReadByIdService), arg0)
}

// Update mocks base method.
func (m *MockstudentService) Update(arg0 models.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockstudentServiceMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockstudentService)(nil).Update), arg0)
}
